version: '3.8'

volumes:
  database-data:

networks:
  default:
    driver: bridge
    
services:
  database:
    container_name: database
    image: 'mysql:8.3.0'
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_ROOT_USER: ${DOCKER_DB_UNAME}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PWD}
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}
      plugin: caching_sha2_password
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-u", "${DOCKER_DB_UNAME}", "-p'${DOCKER_DB_PWD}'"]
      timeout: 6s
      retries: 10
      interval: 5s
      start_interval: 3s
  
  cache:
    container_name: cache
    image: 'redis:7.2.4'
    restart: always
    environment:
      - REDIS_URL=${DOCKER_REDIS_URL}
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DOCKER_REDIS_PASSWORD}
    networks:
      - default

  web:
    container_name: web
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
    ports: 
      - 3000:3000
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
